import {build} from 'esbuild';
import {writeFile,mkdir,readFile} from 'node:fs/promises';
const result=await build({entryPoints:['src/main.jsx'],bundle:true,minify:true,write:false,outdir:'build',format:'iife',platform:'browser',target:['es2022'],define:{'process.env.NODE_ENV':'"production"'},legalComments:'inline'});
const script=result.outputFiles.find(file=>file.path.endsWith('.js')).text;
const css=result.outputFiles.find(file=>file.path.endsWith('.css')).text;
const generated=`// Generated by widgets/wardrobe/build.mjs. Edit the widget source, then rebuild.\nexport const wardrobeScript = ${JSON.stringify(script)};\nexport const wardrobeCss = ${JSON.stringify(css)};\n`;
if(process.argv.includes('--check')){
 if(await readFile('../../src/domains/style/wardrobe-approved-bundle.ts','utf8')!==generated)throw new Error('Wardrobe bundle is stale. Run npm run build:wardrobe.');
 console.log('Wardrobe bundle matches source.');process.exit(0);
}
await mkdir('build',{recursive:true});
await writeFile('build/wardrobe.js',script);
await writeFile('build/wardrobe.css',css);
await writeFile('../../src/domains/style/wardrobe-approved-bundle.ts',generated);
console.log(`Wardrobe candidate: ${Buffer.byteLength(script)} script bytes; ${Buffer.byteLength(css)} CSS bytes`);
